# Instal NumPy

In [1]:
pip install NumPy

Note: you may need to restart the kernel to use updated packages.


# Membuat Array Numpy

In [2]:
import numpy as np

#Membuat array 1D
array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)

#Membuat array 2D
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


# Operasi Matematika pada Array Numpy

In [3]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

#Penjumlahan array
print(a + b)

#Perkalian array
print(a * b)

#Operasi skalar
print(a * 2)

[5 7 9]
[ 4 10 18]
[2 4 6]


# Fungsi Statistik di NumPy

In [7]:
import numpy as np
data = np.array([10, 20, 30, 40, 50])

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)

print(f"Mean: {mean}, Median: {median}, Standard Deviation: {std_dev}")

Mean: 30.0, Median: 30.0, Standard Deviation: 14.142135623730951


# Manipulasi Bentuk Array

In [8]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6])

#Mengubah bentuk array menjadi 2D
reshaped_array = array.reshape(2, 3)
print(reshaped_array)

[[1 2 3]
 [4 5 6]]
